import type { RoadmapDetail, TopicGroup, RoadmapProblemItem } from "../types";

export const SAMPLE_ROADMAP: RoadmapDetail = {
  id: "sample-neetcode-150",
  userId: "sample-user",
  title: "NeetCode 150",
  sourceType: "drive_url",
  sourceUrl: "https://docs.google.com/spreadsheets/d/neetcode-150",
  status: "COMPLETED",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  totalProblems: 180,
  solvedProblems: 34,
  progressPercentage: 18.8,
  roadmapProblems: [],
  topics: [
    {
      topic: "Arrays & Hashing",
      total: 20,
      solved: 12,
      progressPercentage: 60,
      problems: [
        {
          id: "p-1",
          roadmapId: "sample-neetcode-150",
          problemId: "prob-1",
          topic: "Arrays & Hashing",
          originalTitle: "Two Sum",
          originalUrl: "https://leetcode.com/problems/two-sum/",
          originalDifficulty: "EASY",
          orderIndex: 0,
          status: "SOLVED",
          solvedAt: "2026-10-02T14:20:00Z",
          githubSyncStatus: "SYNCED",
          githubRepo: "octocat/neetcode-practice",
          githubCommitSha: "7b4f2c9",
          githubFilePath: "arrays_and_hashing/two_sum.py",
          timeComplexity: "O(n)",
          spaceComplexity: "O(n)",
          aiNotes: "### Core Intuition\nUse a hash table to store complement values `target - num` along with their indices during a single linear scan.\n\n### Key Invariant\nIf `target - num` is already present in our lookup table, we have discovered the pair with constant time lookup.\n\n### Pitfalls\nEnsure you do not use the same element at index `i` twice (e.g., when `num * 2 === target`).",
          userNotes: "Review one-pass hash map trick before technical phone screens.",
          language: "Python",
          code: `def twoSum(nums: list[int], target: int) -> list[int]:
    lookup = {}
    for i, n in enumerate(nums):
        diff = target - n
        if diff in lookup:
            return [lookup[diff], i]
        lookup[n] = i
    return []`,
          problem: {
            id: "prob-1",
            canonicalSlug: "two-sum",
            title: "Two Sum",
            difficulty: "EASY",
            platform: "LeetCode",
            externalUrl: "https://leetcode.com/problems/two-sum/",
          },
        },
        {
          id: "p-2",
          roadmapId: "sample-neetcode-150",
          problemId: "prob-2",
          topic: "Arrays & Hashing",
          originalTitle: "Contains Duplicate II",
          originalUrl: "https://leetcode.com/problems/contains-duplicate-ii/",
          originalDifficulty: "MEDIUM",
          orderIndex: 1,
          status: "SOLVED",
          solvedAt: "2026-10-03T11:15:00Z",
          githubSyncStatus: "SYNCED",
          githubRepo: "octocat/neetcode-practice",
          githubCommitSha: "9a2f1c8",
          githubFilePath: "arrays_and_hashing/contains_duplicate_ii.py",
          timeComplexity: "O(n)",
          spaceComplexity: "O(min(n, k))",
          aiNotes: "### Core Intuition\nMaintain a sliding window of size `k` using a hash set. Check whether each incoming number already exists in the window.",
          language: "Python",
          problem: {
            id: "prob-2",
            canonicalSlug: "contains-duplicate-ii",
            title: "Contains Duplicate II",
            difficulty: "MEDIUM",
            platform: "LeetCode",
            externalUrl: "https://leetcode.com/problems/contains-duplicate-ii/",
          },
        },
        {
          id: "p-3",
          roadmapId: "sample-neetcode-150",
          problemId: "prob-3",
          topic: "Arrays & Hashing",
          originalTitle: "4Sum",
          originalUrl: "https://leetcode.com/problems/4sum/",
          originalDifficulty: "MEDIUM",
          orderIndex: 2,
          status: "SOLVED",
          solvedAt: "2026-10-04T09:40:00Z",
          githubSyncStatus: "SYNCED",
          githubRepo: "octocat/neetcode-practice",
          githubCommitSha: "3c7e8d2",
          githubFilePath: "arrays_and_hashing/4sum.py",
          timeComplexity: "O(n^3)",
          spaceComplexity: "O(1) extra space",
          aiNotes: "### Generalization\nSort the array first to avoid duplicates easily. Fix the first two elements with nested loops, then run two-pointer convergence on the remainder.",
          language: "Python",
          problem: {
            id: "prob-3",
            canonicalSlug: "4sum",
            title: "4Sum",
            difficulty: "MEDIUM",
            platform: "LeetCode",
            externalUrl: "https://leetcode.com/problems/4sum/",
          },
        },
        {
          id: "p-4",
          roadmapId: "sample-neetcode-150",
          problemId: "prob-4",
          topic: "Arrays & Hashing",
          originalTitle: "Product of Array Except Self",
          originalUrl: "https://leetcode.com/problems/product-of-array-except-self/",
          originalDifficulty: "HARD",
          orderIndex: 3,
          status: "NOT_STARTED",
          githubSyncStatus: null, // Dull/dim start icon!
          aiNotes: "### Optimal Approach\nPrefix product pass from left to right, followed by postfix product pass from right to left directly within output array.",
          timeComplexity: "O(n)",
          spaceComplexity: "O(1) excluding output",
          problem: {
            id: "prob-4",
            canonicalSlug: "product-of-array-except-self",
            title: "Product of Array Except Self",
            difficulty: "HARD",
            platform: "LeetCode",
            externalUrl: "https://leetcode.com/problems/product-of-array-except-self/",
          },
        },
        {
          id: "p-5",
          roadmapId: "sample-neetcode-150",
          problemId: "prob-5",
          topic: "Arrays & Hashing",
          originalTitle: "Top K Frequent Elements",
          originalUrl: "https://leetcode.com/problems/top-k-frequent-elements/",
          originalDifficulty: "MEDIUM",
          orderIndex: 4,
          status: "ATTEMPTED",
          githubSyncStatus: "PENDING",
          aiNotes: "### Bucket Sort / Min-Heap\nUse frequency map, then bucket array indexed by count `[0..n]` for linear $O(n)$ time performance.",
          timeComplexity: "O(n)",
          spaceComplexity: "O(n)",
          problem: {
            id: "prob-5",
            canonicalSlug: "top-k-frequent-elements",
            title: "Top K Frequent Elements",
            difficulty: "MEDIUM",
            platform: "LeetCode",
            externalUrl: "https://leetcode.com/problems/top-k-frequent-elements/",
          },
        },
      ],
    },
    {
      topic: "Two Pointers",
      total: 15,
      solved: 0,
      progressPercentage: 0,
      problems: [
        {
          id: "p-6",
          roadmapId: "sample-neetcode-150",
          problemId: "prob-6",
          topic: "Two Pointers",
          originalTitle: "Valid Palindrome",
          originalUrl: "https://leetcode.com/problems/valid-palindrome/",
          originalDifficulty: "EASY",
          orderIndex: 0,
          status: "NOT_STARTED",
          githubSyncStatus: null,
          timeComplexity: "O(n)",
          spaceComplexity: "O(1)",
          aiNotes: "Use two pointers moving inward. Skip non-alphanumeric characters.",
          problem: {
            id: "prob-6",
            canonicalSlug: "valid-palindrome",
            title: "Valid Palindrome",
            difficulty: "EASY",
            platform: "LeetCode",
            externalUrl: "https://leetcode.com/problems/valid-palindrome/",
          },
        },
        {
          id: "p-7",
          roadmapId: "sample-neetcode-150",
          problemId: "prob-7",
          topic: "Two Pointers",
          originalTitle: "Two Sum II - Input Array Is Sorted",
          originalUrl: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
          originalDifficulty: "MEDIUM",
          orderIndex: 1,
          status: "NOT_STARTED",
          githubSyncStatus: null,
          timeComplexity: "O(n)",
          spaceComplexity: "O(1)",
          aiNotes: "Two pointers at left and right extremes. Increment left if sum < target, decrement right if sum > target.",
          problem: {
            id: "prob-7",
            canonicalSlug: "two-sum-ii-input-array-is-sorted",
            title: "Two Sum II - Input Array Is Sorted",
            difficulty: "MEDIUM",
            platform: "LeetCode",
            externalUrl: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/",
          },
        },
        {
          id: "p-8",
          roadmapId: "sample-neetcode-150",
          problemId: "prob-8",
          topic: "Two Pointers",
          originalTitle: "3Sum",
          originalUrl: "https://leetcode.com/problems/3sum/",
          originalDifficulty: "MEDIUM",
          orderIndex: 2,
          status: "NOT_STARTED",
          githubSyncStatus: null,
          timeComplexity: "O(n^2)",
          spaceComplexity: "O(1) extra",
          aiNotes: "Sort array. Iterate element `i`, two-pointer search on remaining suffix. Skip duplicates at every pointer move.",
          problem: {
            id: "prob-8",
            canonicalSlug: "3sum",
            title: "3Sum",
            difficulty: "MEDIUM",
            platform: "LeetCode",
            externalUrl: "https://leetcode.com/problems/3sum/",
          },
        },
      ],
    },
    {
      topic: "Sliding Window",
      total: 12,
      solved: 3,
      progressPercentage: 25,
      problems: [
        {
          id: "p-9",
          roadmapId: "sample-neetcode-150",
          problemId: "prob-9",
          topic: "Sliding Window",
          originalTitle: "Best Time to Buy and Sell Stock",
          originalUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
          originalDifficulty: "EASY",
          orderIndex: 0,
          status: "SOLVED",
          solvedAt: "2026-10-01T10:00:00Z",
          githubSyncStatus: "SYNCED",
          githubRepo: "octocat/neetcode-practice",
          githubCommitSha: "1f8e4b3",
          githubFilePath: "sliding_window/stock.py",
          timeComplexity: "O(n)",
          spaceComplexity: "O(1)",
          aiNotes: "Track minimum price seen so far and update maximum profit at each price step.",
          problem: {
            id: "prob-9",
            canonicalSlug: "best-time-to-buy-and-sell-stock",
            title: "Best Time to Buy and Sell Stock",
            difficulty: "EASY",
            platform: "LeetCode",
            externalUrl: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
          },
        },
        {
          id: "p-10",
          roadmapId: "sample-neetcode-150",
          problemId: "prob-10",
          topic: "Sliding Window",
          originalTitle: "Longest Substring Without Repeating Characters",
          originalUrl: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
          originalDifficulty: "MEDIUM",
          orderIndex: 1,
          status: "REVISE",
          githubSyncStatus: "SYNCED",
          githubRepo: "octocat/neetcode-practice",
          githubCommitSha: "8a4c1f9",
          githubFilePath: "sliding_window/longest_substring.py",
          timeComplexity: "O(n)",
          spaceComplexity: "O(min(m, n))",
          aiNotes: "Sliding window with hash set or character last seen index map to fast-forward the left pointer.",
          problem: {
            id: "prob-10",
            canonicalSlug: "longest-substring-without-repeating-characters",
            title: "Longest Substring Without Repeating Characters",
            difficulty: "MEDIUM",
            platform: "LeetCode",
            externalUrl: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
          },
        },
      ],
    },
  ],
};
